---
- name: Run your database container
  docker_container:
    name: my-db
    image: marvin92/tp-devops-database
    networks:
      - name: my-network
    volumes:
      - db-volume:/var/lib/postgresql/data